---
name: Pod-IkiWiki
version: 0.0.4
author:
  - '"Victor Moral" <victor@taquiones.net>'
abstract: POD translator for ikiwiki's markdown source
license: gpl
resources:
  license: http://opensource.org/licenses/gpl-license.php
requires:
  Pod::Parser: 0
  perl: 0
build_requires:
  Pod::Parser: 0
  Test::More: 0
  Test::NoWarnings: 0
provides:
  Pod::IkiWiki:
    file: lib/Pod/IkiWiki.pm
    version: 0.0.4
generated_by: Module::Build version 0.3
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
